version: "1"
services:
  app:
    image: belazyapi

    build:
      context: .
    command: yarn start
    ports:
      - "3000:3000"
    volumes:
      - .:/opt/app
    
    # environment:
    #   POSTGRES_URI: